name: Demo Workflow
on: workflow_dispatch 
jobs:
  print: 
    runs-on: ubuntu-lates
    steps:
       - name: Print to console
         run: echo Hello GC Actions! 
       - name: Print a few lines
         run: |
          echo First line 
          echo Second Line
  
